module.exports = {
  global: {
    UNEXPECTED_ERROR: "UNEXPECTED_ERROR"
  },
  stations: {
    MISSING_STATION_NAME: "MISSING_STATION_NAME",
    STATION_NAME_TOO_SHORT: "STATION_NAME_TOO_SHORT",
    STATION_NOT_FOUND: "STATION_NOT_FOUND",
    MISSING_STATION_ID: "MISSING_STATION_ID"
  },
  cars: {
    MISSING_CAR_NAME: "MISSING_CAR_NAME",
    MISSING_STATION_ID: "MISSING_STATION_ID",
    STATION_NOT_FOUND: "STATION_NOT_FOUND",
    CAR_NAME_TOO_SHORT: "CAR_NAME_TOO_SHORT",
    CAR_NOT_FOUND: "CAR_NOT_FOUND"
  }
};
